In [4]:
import pandas as pd
import os

In [25]:
from langchain_core.documents import Document
from langchain_text_splitters import RecursiveCharacterTextSplitter

In [13]:
os.getcwd()

'c:\\Users\\Admin\\OneDrive\\Documents\\Sample Projects\\product_recommendation_system\\experiments'

In [14]:
root = os.path.dirname(os.getcwd())

In [15]:
root

'c:\\Users\\Admin\\OneDrive\\Documents\\Sample Projects\\product_recommendation_system'

In [16]:
data_path = os.path.join(root, "data", "flipkart_product_review.csv")

In [17]:
data_path

'c:\\Users\\Admin\\OneDrive\\Documents\\Sample Projects\\product_recommendation_system\\data\\flipkart_product_review.csv'

In [18]:
# def doc_converter(self):
docs = []
df = pd.read_csv(data_path)[['product_id', 'review']]
# for _, row in df.iterrows():    
#     docs.append(Document(
#         page_content=row['review'],
#         metadata={'product_id': row['product_id']}
#     ))
# chunker = RecursiveCharacterTextSplitter(chunk_size=500,chunk_overlap=50)
# chunks = chunker.split_documents(docs)
df.head()
        # return chunk

         product_id                                             review
0  ACCFZGAQJGYCYDCM  1-more flexible2-bass is very high3-sound clar...
1  ACCFZGAQJGYCYDCM     Super sound and good looking I like that prize
2  ACCFZGAQJGYCYDCM  Very much satisfied with the device at this pr...
3  ACCFZGAQJGYCYDCM  Nice headphone, bass was very good and sound i...
4  ACCFZGAQJGYCYDCM  Sound quality super battery backup super quali...

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 450 entries, 0 to 449
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   product_id  450 non-null    object
 1   review      450 non-null    object
dtypes: object(2)
memory usage: 7.2+ KB

In [71]:
df['product_id'].nunique()

9

In [73]:
df[df['product_id']=='ACCFZGAQJGYCYDCM']

          product_id                                             review
0   ACCFZGAQJGYCYDCM  1-more flexible2-bass is very high3-sound clar...
1   ACCFZGAQJGYCYDCM     Super sound and good looking I like that prize
2   ACCFZGAQJGYCYDCM  Very much satisfied with the device at this pr...
3   ACCFZGAQJGYCYDCM  Nice headphone, bass was very good and sound i...
4   ACCFZGAQJGYCYDCM  Sound quality super battery backup super quali...
5   ACCFZGAQJGYCYDCM  Wowwww it's amezing bluetooth nice look, nice ...
6   ACCFZGAQJGYCYDCM  Awesome colour! Amazing experience .. but only...
7   ACCFZGAQJGYCYDCM  For the first time, I am posting a review, jus...
8   ACCFZGAQJGYCYDCM  First of all the Delivery boy is a good guy. N...
9   ACCFZGAQJGYCYDCM  This headphone is good but not that much as i ...
10  ACCFZGAQJGYCYDCM  It's a very good product ... I'm so happy with...
11  ACCFZGAQJGYCYDCM  Nice build quality.. bass is best it self.. vi...
12  ACCFZGAQJGYCYDCM  After using for about 8 days, right side of th...
13  ACCFZGAQJGYCYDCM  Mic is not proper recipient persons can't hear...
14  ACCFZGAQJGYCYDCM  Wow flip cart super fast service like  express...
15  ACCFZGAQJGYCYDCM  Very great product at this price I will assure...
16  ACCFZGAQJGYCYDCM  It's very good and its bass is very high This ...
17  ACCFZGAQJGYCYDCM  Good product. Never used bluetooth headset bef...
18  ACCFZGAQJGYCYDCM  This review is after 1 month of use .Pro:- 1.B...
19  ACCFZGAQJGYCYDCM  I like It Boat HP Sound Quality is bestm best ...
20  ACCFZGAQJGYCYDCM  Hi Seekers, I am writing this review after 2 w...
21  ACCFZGAQJGYCYDCM  Great product.. I loved it.. As I was using le...
22  ACCFZGAQJGYCYDCM  Awesome product happy to have one.Good sound q...
23  ACCFZGAQJGYCYDCM  It's a very good product... I'm so happy with ...
24  ACCFZGAQJGYCYDCM  Amazing product   Sound quality was awesome, i...
25  ACCFZGAQJGYCYDCM  I think it is the best product in this price s...
26  ACCFZGAQJGYCYDCM  Best product at this price loved it. Thank you...
27  ACCFZGAQJGYCYDCM  Excellent voice clarity superb bass for music ...
28  ACCFZGAQJGYCYDCM  This earphone is just awsome yaar , everything...
29  ACCFZGAQJGYCYDCM  It is an amazing product.. For this price... L...
30  ACCFZGAQJGYCYDCM  The product was good enough.. Stylish blur col...
31  ACCFZGAQJGYCYDCM  Boat headset is very clear voice and bass is v...
32  ACCFZGAQJGYCYDCM  A fine product i would say , well crafted desi...
33  ACCFZGAQJGYCYDCM  Good product very fast delivery (with in 36 ho...
34  ACCFZGAQJGYCYDCM  Boat rockerz 235 v2 is the budget blutooth hea...
35  ACCFZGAQJGYCYDCM  If you are a bass lover then blindly go for it...
36  ACCFZGAQJGYCYDCM  Review after about 2months of usage.Before sta...
37  ACCFZGAQJGYCYDCM  Im a jbl user ..boat 235v2 battery is too good...
38  ACCFZGAQJGYCYDCM  The boat 235v2 is really good it's sounds very...
39  ACCFZGAQJGYCYDCM  Above from my expectation, after reading the r...
40  ACCFZGAQJGYCYDCM  I brought this product as I was looking for a ...
41  ACCFZGAQJGYCYDCM  Ti's is my first Bluetooth headset it is wonde...
42  ACCFZGAQJGYCYDCM  Very decent look product. Give superb bass. Mi...
43  ACCFZGAQJGYCYDCM  Good quality and good product you have to take...
44  ACCFZGAQJGYCYDCM  Awsome Sound Quality 5 * !!Bass Is Awsome 5* !...
45  ACCFZGAQJGYCYDCM  It so nice but nickband so tall but otherwise ...
46  ACCFZGAQJGYCYDCM  It's a Awesome purchase. Value for money. I ca...
47  ACCFZGAQJGYCYDCM  Very nice very satisfied and sound quality ver...
48  ACCFZGAQJGYCYDCM  First of all it looks very perfect and is non ...
49  ACCFZGAQJGYCYDCM  I think for this price range, it's one of the ...

In [76]:
grouped_df = df.groupby('product_id',as_index=False)['review'].sum()

In [77]:
grouped_df.reset_index()

   index        product_id                                             review
0      0  ACCEVQZABYWJHRHF  Very Good sound clarity with bass, build quali...
1      1  ACCFHGZFS7GB9CVM  I will tell you some hidden features that you ...
2      2  ACCFKYE2ARGG67WC  Nice head set good fit nice quality good to ha...
3      3  ACCFR3Q77R6RRGAC  first of all with mi 18 watt charger,it got fu...
4      4  ACCFSDGXX3S6DVBG  (1) Worth of the money 💰(2) Nice design & comf...
5      5  ACCFSKBJYWZKXGCP  I am very happy with this product. The U&I Tit...
6      6  ACCFVA3KZ2EYMYX3  Good battery 🔋 👌 Sound awesome 👌 Bass 🔊  super...
7      7  ACCFVWN4PGNTEFGY  Amazing Product, bass is amazing and easy to c...
8      8  ACCFZGAQJGYCYDCM  1-more flexible2-bass is very high3-sound clar...

In [78]:
grouped_df

         product_id                                             review
0  ACCEVQZABYWJHRHF  Very Good sound clarity with bass, build quali...
1  ACCFHGZFS7GB9CVM  I will tell you some hidden features that you ...
2  ACCFKYE2ARGG67WC  Nice head set good fit nice quality good to ha...
3  ACCFR3Q77R6RRGAC  first of all with mi 18 watt charger,it got fu...
4  ACCFSDGXX3S6DVBG  (1) Worth of the money 💰(2) Nice design & comf...
5  ACCFSKBJYWZKXGCP  I am very happy with this product. The U&I Tit...
6  ACCFVA3KZ2EYMYX3  Good battery 🔋 👌 Sound awesome 👌 Bass 🔊  super...
7  ACCFVWN4PGNTEFGY  Amazing Product, bass is amazing and easy to c...
8  ACCFZGAQJGYCYDCM  1-more flexible2-bass is very high3-sound clar...

In [88]:
pd.set_option('display.max_rows',None)

In [92]:
review = grouped_df[grouped_df['product_id']=='ACCFZGAQJGYCYDCM']['review']

In [95]:
len(str(review))

82

In [21]:
 for _, row in df.iterrows():    
            docs.append(Document(
                page_content=row['review'],
                metadata={'product_id': row['product_id']}
            ))

In [23]:
docs[:10]

[Document(metadata={'product_id': 'ACCFZGAQJGYCYDCM'}, page_content="1-more flexible2-bass is very high3-sound clarity is good 4-battery back up to 6 to 8 hour's 5-main thing is fastest charging system is available in that. Only 20 min charge and get long up to 4 hours back up 6-killing look awesome 7-for gaming that product does not support 100% if you want for gaming then I'll recommend you please don't buy but you want for only music then this product is very well for you.. 8-no more wireless headphones are comparing with that headphones at this pric..."),
 Document(metadata={'product_id': 'ACCFZGAQJGYCYDCM'}, page_content='Super sound and good looking I like that prize'),
 Document(metadata={'product_id': 'ACCFZGAQJGYCYDCM'}, page_content='Very much satisfied with the device at this price point being from an awesome brand. Design wise , I liked it more than rockerz 255 model.Bought the model blindly on its very first day with zero reviews and it was a wonderful choice I must say.Bluetooth 5.0 enables us to connect devices simultaneously. And vibration motor for calls , its too good.'),
 Document(metadata={'product_id': 'ACCFZGAQJGYCYDCM'}, page_content='Nice headphone, bass was very good and sound is clear. I am purchase for calling purpose and best choice even riding on bike wear in one ear and opposite end voice was clear and no complaint for calling.. Battery backup 1 full day'),
 Document(metadata={'product_id': 'ACCFZGAQJGYCYDCM'}, page_content='Sound quality super battery backup super quality super this price range super and this value for money'),
 Document(metadata={'product_id': 'ACCFZGAQJGYCYDCM'}, page_content="Wowwww it's amezing bluetooth nice look, nice price, nice battery back up, I love always flipkart product's and Flipkart replacement and refund policy, you can return or refund after received a demegzed product"),
 Document(metadata={'product_id': 'ACCFZGAQJGYCYDCM'}, page_content='Awesome colour! Amazing experience .. but only the charging data cable is not of good quality and adjustable clip is not so tight.'),
 Document(metadata={'product_id': 'ACCFZGAQJGYCYDCM'}, page_content="For the first time, I am posting a review, just because the product compelled me to do so. Icouldn't find a single aspect missed or mis-handled by Boat. Well this is called, quality engineering. Well, some people say Boat enhances bass and thus compensates with clarity, but I would give my neutral and true feedbackBass : 10/10Clarity : 9/10Comfort ease n looks : 15/10Features :10/10The best buy from flipkart yet.."),
 Document(metadata={'product_id': 'ACCFZGAQJGYCYDCM'}, page_content='First of all the Delivery boy is a good guy. Nice receive and responce. Product is super. Packing also good.  I fell Red color is not sufficient for me. Otherwise totally awesome product. Delivery is too long. Iam taking one week after booking. Thankyou flipcart and boat 235v2 also.'),
 Document(metadata={'product_id': 'ACCFZGAQJGYCYDCM'}, page_content="This headphone is good but not that much as i expected*Pros- 1Good battery backup             2Good sound quality*Cons-1 There's a voice gap between video activity and voice. Voice comes after video activity not both comes together. It is ok when you watch movies and music but if you play pubg with it you will clearly feel the big gap it matters a lot for me. It is not working after 4 month very much disappointedOverall not goodDon't buy please")]

In [54]:
chunker = RecursiveCharacterTextSplitter(chunk_size=200,chunk_overlap=50,separators = ['.'])
chunks = chunker.split_documents(docs[:10])

In [55]:
chunks

[Document(metadata={'product_id': 'ACCFZGAQJGYCYDCM'}, page_content="1-more flexible2-bass is very high3-sound clarity is good 4-battery back up to 6 to 8 hour's 5-main thing is fastest charging system is available in that"),
 Document(metadata={'product_id': 'ACCFZGAQJGYCYDCM'}, page_content=". Only 20 min charge and get long up to 4 hours back up 6-killing look awesome 7-for gaming that product does not support 100% if you want for gaming then I'll recommend you please don't buy but you want for only music then this product is very well for you"),
 Document(metadata={'product_id': 'ACCFZGAQJGYCYDCM'}, page_content='.. 8-no more wireless headphones are comparing with that headphones at this pric...'),
 Document(metadata={'product_id': 'ACCFZGAQJGYCYDCM'}, page_content='Super sound and good looking I like that prize'),
 Document(metadata={'product_id': 'ACCFZGAQJGYCYDCM'}, page_content='Very much satisfied with the device at this price point being from an awesome brand. Design wise , I liked it more than rockerz 255 model'),
 Document(metadata={'product_id': 'ACCFZGAQJGYCYDCM'}, page_content='.Bought the model blindly on its very first day with zero reviews and it was a wonderful choice I must say.Bluetooth 5.0 enables us to connect devices simultaneously'),
 Document(metadata={'product_id': 'ACCFZGAQJGYCYDCM'}, page_content='.0 enables us to connect devices simultaneously. And vibration motor for calls , its too good.'),
 Document(metadata={'product_id': 'ACCFZGAQJGYCYDCM'}, page_content='Nice headphone, bass was very good and sound is clear'),
 Document(metadata={'product_id': 'ACCFZGAQJGYCYDCM'}, page_content='. I am purchase for calling purpose and best choice even riding on bike wear in one ear and opposite end voice was clear and no complaint for calling.. Battery backup 1 full day'),
 Document(metadata={'product_id': 'ACCFZGAQJGYCYDCM'}, page_content='Sound quality super battery backup super quality super this price range super and this value for money'),
 Document(metadata={'product_id': 'ACCFZGAQJGYCYDCM'}, page_content="Wowwww it's amezing bluetooth nice look, nice price, nice battery back up, I love always flipkart product's and Flipkart replacement and refund policy, you can return or refund after received a demegzed product"),
 Document(metadata={'product_id': 'ACCFZGAQJGYCYDCM'}, page_content='Awesome colour! Amazing experience .. but only the charging data cable is not of good quality and adjustable clip is not so tight.'),
 Document(metadata={'product_id': 'ACCFZGAQJGYCYDCM'}, page_content="For the first time, I am posting a review, just because the product compelled me to do so. Icouldn't find a single aspect missed or mis-handled by Boat. Well this is called, quality engineering"),
 Document(metadata={'product_id': 'ACCFZGAQJGYCYDCM'}, page_content='. Well, some people say Boat enhances bass and thus compensates with clarity, but I would give my neutral and true feedbackBass : 10/10Clarity : 9/10Comfort ease n looks : 15/10Features :10/10The best buy from flipkart yet'),
 Document(metadata={'product_id': 'ACCFZGAQJGYCYDCM'}, page_content='..'),
 Document(metadata={'product_id': 'ACCFZGAQJGYCYDCM'}, page_content='First of all the Delivery boy is a good guy. Nice receive and responce. Product is super. Packing also good.  I fell Red color is not sufficient for me. Otherwise totally awesome product'),
 Document(metadata={'product_id': 'ACCFZGAQJGYCYDCM'}, page_content='. Otherwise totally awesome product. Delivery is too long. Iam taking one week after booking. Thankyou flipcart and boat 235v2 also.'),
 Document(metadata={'product_id': 'ACCFZGAQJGYCYDCM'}, page_content="This headphone is good but not that much as i expected*Pros- 1Good battery backup             2Good sound quality*Cons-1 There's a voice gap between video activity and voice"),
 Document(metadata={'product_id': 'ACCFZGAQJGYCYDCM'}, page_content='. Voice comes after video activity not both comes together. It is ok when you watch movies and music but if you play pubg with it you will clearly feel the big gap it matters a lot for me'),
 Document(metadata={'product_id': 'ACCFZGAQJGYCYDCM'}, page_content=". It is not working after 4 month very much disappointedOverall not goodDon't buy please")]

In [43]:
# Token Chunking
from langchain_text_splitters import TokenTextSplitter

In [56]:
chunker = TokenTextSplitter(chunk_size=200, chunk_overlap=20,separators = ['.'])
chunks = chunker.split_documents(docs[:10])

TypeError: TextSplitter.__init__() got an unexpected keyword argument 'separators'

In [52]:
chunks

[Document(metadata={'product_id': 'ACCFZGAQJGYCYDCM'}, page_content="1-more flexible2-bass is very high3-sound clarity is good 4-battery back up to 6 to 8 hour's 5-main thing is fastest charging system is available in that. Only 20 min charge and get long up to 4 hours back up 6-killing look awesome 7-for gaming that product does not support 100% if you want for gaming then I'll recommend you please don't buy but you want for only music then this product is very well for you.. 8-no more wireless headphones are comparing with that headphones at this pric..."),
 Document(metadata={'product_id': 'ACCFZGAQJGYCYDCM'}, page_content='Super sound and good looking I like that prize'),
 Document(metadata={'product_id': 'ACCFZGAQJGYCYDCM'}, page_content='Very much satisfied with the device at this price point being from an awesome brand. Design wise , I liked it more than rockerz 255 model.Bought the model blindly on its very first day with zero reviews and it was a wonderful choice I must say.Bluetooth 5.0 enables us to connect devices simultaneously. And vibration motor for calls , its too good.'),
 Document(metadata={'product_id': 'ACCFZGAQJGYCYDCM'}, page_content='Nice headphone, bass was very good and sound is clear. I am purchase for calling purpose and best choice even riding on bike wear in one ear and opposite end voice was clear and no complaint for calling.. Battery backup 1 full day'),
 Document(metadata={'product_id': 'ACCFZGAQJGYCYDCM'}, page_content='Sound quality super battery backup super quality super this price range super and this value for money'),
 Document(metadata={'product_id': 'ACCFZGAQJGYCYDCM'}, page_content="Wowwww it's amezing bluetooth nice look, nice price, nice battery back up, I love always flipkart product's and Flipkart replacement and refund policy, you can return or refund after received a demegzed product"),
 Document(metadata={'product_id': 'ACCFZGAQJGYCYDCM'}, page_content='Awesome colour! Amazing experience .. but only the charging data cable is not of good quality and adjustable clip is not so tight.'),
 Document(metadata={'product_id': 'ACCFZGAQJGYCYDCM'}, page_content="For the first time, I am posting a review, just because the product compelled me to do so. Icouldn't find a single aspect missed or mis-handled by Boat. Well this is called, quality engineering. Well, some people say Boat enhances bass and thus compensates with clarity, but I would give my neutral and true feedbackBass : 10/10Clarity : 9/10Comfort ease n looks : 15/10Features :10/10The best buy from flipkart yet.."),
 Document(metadata={'product_id': 'ACCFZGAQJGYCYDCM'}, page_content='First of all the Delivery boy is a good guy. Nice receive and responce. Product is super. Packing also good.  I fell Red color is not sufficient for me. Otherwise totally awesome product. Delivery is too long. Iam taking one week after booking. Thankyou flipcart and boat 235v2 also.'),
 Document(metadata={'product_id': 'ACCFZGAQJGYCYDCM'}, page_content="This headphone is good but not that much as i expected*Pros- 1Good battery backup             2Good sound quality*Cons-1 There's a voice gap between video activity and voice. Voice comes after video activity not both comes together. It is ok when you watch movies and music but if you play pubg with it you will clearly feel the big gap it matters a lot for me. It is not working after 4 month very much disappointedOverall not goodDon't buy please")]